// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionTracker.Models;

#nullable disable

namespace NutritionTracker.Migrations
{
    [DbContext(typeof(NutritionContext))]
    [Migration("20251201022720_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DishFoods", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("DishFoods");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            FoodId = 1
                        },
                        new
                        {
                            DishId = 1,
                            FoodId = 2
                        });
                });

            modelBuilder.Entity("MealFoods", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.HasKey("FoodId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("MealFoods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            MealId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            MealId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            MealId = 2
                        },
                        new
                        {
                            FoodId = 4,
                            MealId = 2
                        },
                        new
                        {
                            FoodId = 2,
                            MealId = 2
                        });
                });

            modelBuilder.Entity("NutritionTracker.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            Date = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DayId = 2,
                            Date = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NutritionTracker.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Name = "Chicken & Rice"
                        },
                        new
                        {
                            DishId = 2,
                            Name = "Broccoli Stir Fry"
                        });
                });

            modelBuilder.Entity("NutritionTracker.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("DishId")
                        .IsUnique();

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            FavoriteId = 1,
                            DishId = 1
                        },
                        new
                        {
                            FavoriteId = 2,
                            DishId = 2
                        });
                });

            modelBuilder.Entity("NutritionTracker.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Calories = 165.0,
                            Carbohydrates = 0.0,
                            Fat = 3.6000000000000001,
                            Name = "Chicken Breast",
                            Protein = 31.0
                        },
                        new
                        {
                            FoodId = 2,
                            Calories = 130.0,
                            Carbohydrates = 28.0,
                            Fat = 0.29999999999999999,
                            Name = "White Rice",
                            Protein = 2.7000000000000002
                        },
                        new
                        {
                            FoodId = 3,
                            Calories = 55.0,
                            Carbohydrates = 11.0,
                            Fat = 0.59999999999999998,
                            Name = "Broccoli",
                            Protein = 3.7000000000000002
                        },
                        new
                        {
                            FoodId = 4,
                            Calories = 119.0,
                            Carbohydrates = 0.0,
                            Fat = 13.5,
                            Name = "Olive Oil",
                            Protein = 0.0
                        });
                });

            modelBuilder.Entity("NutritionTracker.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("MealId");

                    b.HasIndex("DayId");

                    b.HasIndex("DishId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            DayId = 1,
                            DishId = 1
                        },
                        new
                        {
                            MealId = 2,
                            DayId = 2,
                            DishId = 2
                        });
                });

            modelBuilder.Entity("DishFoods", b =>
                {
                    b.HasOne("NutritionTracker.Models.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealFoods", b =>
                {
                    b.HasOne("NutritionTracker.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Models.Favorite", b =>
                {
                    b.HasOne("NutritionTracker.Models.Dish", "Dish")
                        .WithOne("Favorite")
                        .HasForeignKey("NutritionTracker.Models.Favorite", "DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("NutritionTracker.Models.Meal", b =>
                {
                    b.HasOne("NutritionTracker.Models.Day", "Day")
                        .WithMany("Meals")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Models.Dish", "Dish")
                        .WithMany("Meals")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("NutritionTracker.Models.Day", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutritionTracker.Models.Dish", b =>
                {
                    b.Navigation("Favorite")
                        .IsRequired();

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
